### ISSUE TITLE
threads help 2.11.2021

### ISSUE THREAD

**Issue by Grant451** [C3sarz/CIS520-G17#1]
not an issue, just helpful material: 
pintos documentation: 
[pintos documentation.pdf](https://github.com/C3sarz/CIS520-G17/files/5969568/pintos.documentation.pdf)

helpful video about threads in pintos: [https://www.youtube.com/watch?v=Oe9HsiCZOIc](url)

WIP

**Comment by Grant451** [comment]
about page 68 of the pintos documentation is where threads are covered.

**Comment by C3sarz** [comment]
awesome, thanks!
